spring:
  kafka:
    bootstrap-servers: ${app.kafka.servers}
    consumer:
      group-id: ${app.kafka.group-id}
  flyway:
    locations: "classpath:db/migration/{vendor}"

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 1d
      chain:
        strategy:
          content:
            enabled: true
            paths: /**/*.js,/**/*.css,/**/*.svg,/**/*.jpeg

keycloak:
  gpas:
    token-url: http://localhost:8082/auth/realms/mv64/protocol/openid-connect/token
    client-id: soap
    client-secret: b46TDsluFt9G751pyUKmMQlFhAceRT17
    username: sys-ccc-ldap
    password: KL3P7Cf1HmTW9Pk7tZA

  diz:
    token-url: https://medver-keycloak.srv.med.uni-muenchen.de/auth/realms/broadconsent/protocol/openid-connect/token
    client-id: fhir
    client-secret: b46TDsluFt9G751pyUKmMQlFhAceRT17
    username: sys-ccc-ldap
    password: KL3P7Cf1HmTW9Pk7tZA



server:
  forward-headers-strategy: framework
