spring:
  kafka:
    bootstrap-servers: ${app.kafka.servers}
    consumer:
      group-id: ${app.kafka.group-id}
  flyway:
    locations: "classpath:db/migration/{vendor}"

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 1d
      chain:
        strategy:
          content:
            enabled: true
            paths: /**/*.js,/**/*.css,/**/*.svg,/**/*.jpeg

keycloak:
  gpas:
    token-url: ${KEYCLOAK_GPAS_TOKEN_URL}
    client-id: ${KEYCLOAK_GPAS_CLIENT_ID}
    client-secret: ${KEYCLOAK_GPAS_CLIENT_SECRET}
    username: ${KEYCLOAK_GPAS_USERNAME}
    password: ${KEYCLOAK_GPAS_PASSWORD}

  diz:
    token-url: ${KEYCLOAK_DIZ_TOKEN_URL}
    client-id: ${KEYCLOAK_DIZ_CLIENT_ID}
    client-secret: ${KEYCLOAK_DIZ_CLIENT_SECRET}
    username: ${KEYCLOAK_DIZ_USERNAME}
    password: ${KEYCLOAK_DIZ_PASSWORD}

diz-consent:
  endpoint: ${DIZ_CONSENT_ENDPOINT}

gpas:
  wsdl-url: ${GPAS_WSDL_URL}
app:
  pseudonymize:
    generator: ${PSEUDONYMIZE_METHOD}
  rest:
    uri: ${DIP_ENDPOINT}
  debug: ${DEBUG}

server:
  forward-headers-strategy: framework
