spring:
  kafka:
    bootstrap-servers: ${app.kafka.servers}
    consumer:
      group-id: ${app.kafka.group-id}
  flyway:
    locations: "classpath:db/migration/{vendor}"

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 1d
      chain:
        strategy:
          content:
            enabled: true
            paths: /**/*.js,/**/*.css,/**/*.svg,/**/*.jpeg

keycloak:
  token-url: ${KEYCLOAK_TOKEN_URL}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  username: ${KEYCLOAK_USERNAME}
  password: ${KEYCLOAK_PASSWORD}

gpas:
  wsdl-url: ${GPAS_WSDL_URL}



server:
  forward-headers-strategy: framework
